// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/customers-list/AccessibilityReadability.tsx": () => import("../components/mockups/customers-list/AccessibilityReadability.tsx"),
  "./components/mockups/customers-list/AffordanceVisibility.tsx": () => import("../components/mockups/customers-list/AffordanceVisibility.tsx"),
  "./components/mockups/customers-list/HierarchyClarity.tsx": () => import("../components/mockups/customers-list/HierarchyClarity.tsx"),
  "./components/mockups/home-variants/CommandDashboard.tsx": () => import("../components/mockups/home-variants/CommandDashboard.tsx"),
  "./components/mockups/home-variants/NextActionFocus.tsx": () => import("../components/mockups/home-variants/NextActionFocus.tsx"),
  "./components/mockups/home-variants/PolishedSections.tsx": () => import("../components/mockups/home-variants/PolishedSections.tsx"),
  "./components/mockups/home-variants/TodayTimeline.tsx": () => import("../components/mockups/home-variants/TodayTimeline.tsx"),
  "./components/mockups/home-variants/UrgencyFeed.tsx": () => import("../components/mockups/home-variants/UrgencyFeed.tsx"),
  "./components/mockups/home-variants/WarmEditorial.tsx": () => import("../components/mockups/home-variants/WarmEditorial.tsx"),
  "./components/mockups/signin-approaches/Conversational.tsx": () => import("../components/mockups/signin-approaches/Conversational.tsx"),
  "./components/mockups/signin-approaches/DualAction.tsx": () => import("../components/mockups/signin-approaches/DualAction.tsx"),
  "./components/mockups/signin-approaches/EditorialCraft.tsx": () => import("../components/mockups/signin-approaches/EditorialCraft.tsx"),
  "./components/mockups/signin-approaches/SplitPreview.tsx": () => import("../components/mockups/signin-approaches/SplitPreview.tsx")
};
