// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-variants/CommandDashboard.tsx": () => import("../components/mockups/home-variants/CommandDashboard.tsx"),
  "./components/mockups/home-variants/NextActionFocus.tsx": () => import("../components/mockups/home-variants/NextActionFocus.tsx"),
  "./components/mockups/home-variants/TodayTimeline.tsx": () => import("../components/mockups/home-variants/TodayTimeline.tsx"),
  "./components/mockups/home-variants/UrgencyFeed.tsx": () => import("../components/mockups/home-variants/UrgencyFeed.tsx")
};
